<?php
//$form_action = $RELADDRESS . 'form/' . $_SESSION['us_state'] . '/patientInfo';
?>
<div class="pagecontent">
<h3>User Agreement and Legal & Medical Disclaimer</h3>
<p><span class="bold">AGREEMENT</span> — This legal agreement governs your use of Patietproxy.com (the "site"). An important function of this agreement is to alert you that the data presented on the site is not warranted or otherwise guaranteed and that the content on the site is not medical or legal advice suitable for any situation. Please read this carefully. If you understand these terms and agree to abide by them click "CONTINUE" below. If you do not understand them or agree to them, do not click "CONTINUE" and please do not use these services. By clicking "CONTINUE" below you agree that you have read and understand these conditions and consent to abide by them.</p> 
<p><span class="bold">TERMS</span></p> 
<p><span class="bold">LIABILITY</span> — By accessing the information on this website and/or creating and printing your health care proxy/living will online, you agree that Patient Proxy shall not be liable to you or any one else for any loss or injury caused in procuring, compiling, using, or delivering the information. In no event will Patient Proxy be liable to you or anyone else for any action taken by you in reliance on such information or for any consequential, special or similar damages.</p>
<p><span class="bold">NO FALSE OR MISLEADING INFORMATION</span> — You shall not provide any false information in connection with the use of this site, and you take full responsibility for the accurate and complete expression of your own wishes. In any case when you use incorrect information within the site or information you enter becomes outdated or misleading, you hold Patient Proxy harmless for any consequences of this incorrect, misleading, or outdated information.</p>
<p><span class="bold">GENERAL DISCLAIMER</span> — WHEREAS THE INFORMATION ON THIS SITE COMES FROM A VARIETY OF SOURCES AND IS SUBJECT TO CHANGE WITHOUT NOTICE, PATIENT PROXY MAKES NO WARRANTY, EITHER EXPRESS OR IMPLIED, REGARDING THE COMPLETENESS, ACCURACY OR CURRENCY OF THIS INFORMATION NOR ITS SUITABILITY FOR ANY PARTICULAR PURPOSE. THIS SITE ALSO CONTAINS HYPERTEXT LINKS TO WEBSITES CREATED AND CONTROLLED BY OTHER ORGANIZATIONS. THESE LINKS ARE PROVIDED FOR YOUR CONVENIENCE AND ARE NOT INTENDED AS AN ENDORSEMENT BY PATIENT PROXY OF THE ORGANIZATIONS OPERATING THESE SITES NOR AS A WARRANTY OF THE INFORMATION THEY CONTAIN.</p>
<p><span class="bold">NO LEGAL ADVICE</span> — The site and all of its content is provided as general information only, and no portion of the site nor the site in its entirety is intended to serve as legal advice, counsel, or services regarding any particular situation. The content of the site should not be considered complete, nor should it be relied on for or in any way serve as a substitute for consultation with qualified legal professionals.</p>
<p><span class="bold">NO MEDICAL ADVICE</span> — Neither the site nor any of its content is intended to serve as medical advice or aide in the diagnosis or treatment of any ailment, disease, malady, or medical situation whatsoever. The content of the site should not be considered complete, nor should it be relied on to suggest a course of treatment or action or as a substitute for consultations with qualified health professionals.</p>
<p><span class="bold">INDEMNIFICATION</span> — You hereby indemnify and hold harmless Patient Proxy and its directors, officers, employees, control persons, vendors, licensors and agents, from and against any and all claims, actions, proceedings, losses, liabilities, damages, costs and expenses (including reasonable attorney's and experts' fees and costs) arising out of or related to (i) any use or access by you (or on your behalf) of the website; (ii) any breach by you of any agreements, or representations and warranties contained in these terms and conditions, (iii) any access to or use of the website by you in violation of any rights of the Registry or any third party, including, but not limited to, copyright, patent, trade secret, trademark, or other intellectual property rights and publicity and privacy rights, (iv) any access to or use of the website by you in violation of any applicable law, rule or regulation, or (v) any unauthorized access of, or through, the website to any computer system.</p>
<p><span class="bold">OWNERSHIP AND OTHER INTELLECTUAL PROPERTY RIGHTS</span>--This site and all its pages are copyrighted by Patient Proxy, &copy; 2011 all rights reserved. The only exceptions are materials copyrighted by our licensors, used here by permission. With respect to all the materials on this site, you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such information. If you send us ideas or concepts through the Internet, including e-mail, you are giving us ownership of the ideas or concepts, and we are free to use these ideas or concepts without paying you or obtaining your consent.</p>
<p><span class="bold">CHOICE OF LAW AND PERSONAL JURISDICTION; JURY TRIAL</span>--This website is created and controlled by us in the State of Wisconsin, U.S.A. The laws of the State of Wisconsin govern any disputes between you and us arising in connection with this agreement, without giving effect to any principles of conflicts of laws.</p>
<p>SOLE AND EXCLUSIVE JURISDICTION FOR ANY ACTION OR PROCEEDING ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL BE IN AN APPROPRIATE STATE COURT LOCATED IN THE COUNTY OF DANE, STATE OF WISCONSIN, OR, IN CASES INVOLVING BONA FIDE FEDERAL QUESTIONS, THE UNITED STATES DISTRICT COURT FOR THE WESTERN DISTRICT OF WISCONSIN, MADISON, AND THE PARTIES UNCONDITIONALLY WAIVE THEIR RESPECTIVE RIGHTS TO A JURY TRIAL.</p>

<!--<form action="<?php echo $form_action; ?>" method="POST">
<input type="hidden" name="legal_agreed" value="yes" />
<button type="submit" class="nextbutton">CONTINUE</button>
<a href="<?php //echo $RELADDRESS . '/form/map/'; ?>" title="" class="backbutton">BACK</a>
</form>-->
</div>